# Generated by Django 5.2 on 2025-05-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_auto_20250419_2054"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="name",
            new_name="username",
        ),
    ]
