# Generated by Django 5.2 on 2025-05-16 18:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_name_account_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="default_profile_uxlg3a.jpg",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
