# Generated by Django 5.2 on 2025-05-09 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webchat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="messages",
            old_name="timestamp_create",
            new_name="timestamp_created",
        ),
        migrations.RenameField(
            model_name="messages",
            old_name="timestamp_update",
            new_name="timestamp_updated",
        ),
        migrations.AlterField(
            model_name="messages",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="webchat.conversationmodel",
            ),
        ),
    ]
