# Generated by Django 5.2 on 2025-04-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = []
