# Generated by Django 5.2 on 2025-04-24 13:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_auto_20250419_2054"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="server_image",
            new_name="server_icon",
        ),
        migrations.AddField(
            model_name="server",
            name="banner_image",
            field=cloudinary.models.CloudinaryField(
                default="default_server_uxlg3a.jpg",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
