# Generated by Django 5.2 on 2025-04-24 13:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_rename_server_image_server_server_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="banner_image",
            field=cloudinary.models.CloudinaryField(
                default="default_server_uxlg3a.jpg",
                max_length=255,
                verbose_name="server_banner",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="server_icon",
            field=cloudinary.models.CloudinaryField(
                default="default_server_uxlg3a.jpg",
                max_length=255,
                verbose_name="server_icon",
            ),
        ),
    ]
