# Generated by Django 5.2 on 2025-04-24 13:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0004_alter_server_banner_image_alter_server_server_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="banner_image",
            field=cloudinary.models.CloudinaryField(
                default="default_server_uxlg3a.jpg",
                max_length=255,
                verbose_name="server banner",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="server_icon",
            field=cloudinary.models.CloudinaryField(
                default="default_server_uxlg3a.jpg",
                max_length=255,
                verbose_name="server icon",
            ),
        ),
    ]
