# Generated by Django 5.2 on 2025-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0005_alter_server_banner_image_alter_server_server_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="is_private",
            field=models.BooleanField(default=True),
        ),
    ]
