# Generated by Django 5.2 on 2025-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_rename_name_account_username"),
        ("server", "0006_server_is_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="members",
            field=models.ManyToManyField(related_name="servers", to="account.account"),
        ),
    ]
