# Generated by Django 5.2 on 2025-05-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0007_alter_server_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="type",
            field=models.CharField(
                choices=[("text", "Text")], default="text", max_length=5
            ),
        ),
    ]
